### ISSUE TITLE
Sound made by unseen pawn stays constant instead of phasing

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#147]
I threw a stone to make a pawn investigate where I could hear them moving, and their sound made a constant wave that didn't fade.

**Comment by MicroChasm** [comment]
[issue147.txt](https://github.com/nsmryan/RustRoguelike/files/5013512/issue147.txt)

**Comment by nsmryan** [comment]
Looking into this, somehow the sound effect seems to be generated multiple times. There are 16 effects being animated once the sound completely saturates the area.
I haven't figured out where they are generated from. My thinking is that there is some function that creates a sound message that is called somewhere it shouldn't be. However, as far as I can tell, all sound messages are creating while processing other message, and since you can keep moving once this happens we shouldn't be in a message loop.

**Comment by nsmryan** [comment]
Okay, I got it. When adding the impressions, I changed how animations are reported once updated (changing frames, etc). I did not correctly set the "completion" flag for chained animations, so when the stone hits the target, its chained animation of playing a sound kept getting played because it was never flagged as complete.

**Comment by MicroChasm** [comment]
Running the test document seems to work, as does experimenting on my own. c
