### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by davidskeck** [nsmryan/RustRoguelike#313]
Hello,

I am trying to build and run this game, but I am getting an issue after calling `cargo run`. Note that I do have SDL2 installed.

Here's the issue I'm seeing:

```
error: linking with `cc` failed: exit status: 1
...
  = note: /usr/bin/ld: cannot find -lSDL2_ttf
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error; 2 warnings emitted

error: could not compile `roguelike_main`

To learn more, run the command again with --verbose.
```

Any ideas? I am on Pop!_OS 21.04.

**Comment by nsmryan** [comment]
Thanks for giving this a try!
I expect that the problem is that you have SDL installed, but not SDL_ttf (the true type font component we use for rendering text).
I'm not particularly familiar with Pop, but whatever its package manager is, it can likely install this as a separate package.
If you get a similar problem with SDL_image, it is likely to cause the same problem. These are the only two SDL components we use besides SDL itself.
If this fixes the problem then I will add some text to the README.

If you get the game to compile you can be our first playtester!

**Comment by davidskeck** [comment]
Of course! It sounds fun!

I got it working after installing the `libsdl2-ttf-dev` package and now I am a playtester! I haven't played much but I wanted to let you know I got it working! I'll report back with any findings/fun occuring!
