### ISSUE TITLE
Cool Spells

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#32]
Here are some cool spells from other games.  I will go into more detail later, this post was lost twice  already and I'm not retyping it a third time.

Catacomb Kids:
Blink
Portal

DCSS:
Passage of Golubria
Lee's Rapid Deconstruction
Fulminant Prism

Summoning things is cool in many games.

**Comment by j0e1GMR** [comment]
Cinco Paus is interesting because of how the objects interact.  Abilities can be applied in different orders.
Here are some examples:
Create a shrimp
Kill a shrimp and heal one
Make an explosion
If the beam passes through the center, an earthquake causes one damage to all monsters
Convert a ghost to your side
If a monster has taken at least damage previously, it is now killed
If a monster has more health than you, it is now killed
Kills an enemy if it occupies the square that the beam ends at
The beam goes around corners
If the beam hits a monster that is on a square where a monster previously died, the monster is now killed
Hitting the right wall gives you a charged melee attack
Hitting a wall spawns a treasure
Creates thorns

**Comment by j0e1GMR** [comment]
Something DCSS does really well is to iterate on every game mechanic.  So with the sound system, there are races that make more or less sound, gods that make more or less sound, and traps that cause sound.  For LOS, there is a race that gives you +1 LOS and a spell that gives you -1.  There is are races that modifies how health works, one that modifies how skill training works, one that modifies how food works. 

Michael Brogue's games are also good at the idea of taking a characteristic of roguelikes and iterating on it, doing something new.  Cinco Paus is about item identification, and Imbroglio connects attacking with positioning.

**Comment by j0e1GMR** [comment]
The most interesting build in Imbroglio, to me, is the movement-based one.  They can use a special ability to move against an outer wall and jump to the opposite side of the map, killing an enemy if they land on one. You can pair these abilities with attack tiles that teleport you when you attack, tiles that do ranged attacks (but don't let you move closer to an enemy, you can only attack from this tile or move away from an enemy), and tiles that let you move through a wall at the cost of a magic point (losing all of your magic kills you). 

Like all characters in this game, this one has a disadvantage, which is that the star you need to collect always spawns far away from your current position.
