### ISSUE TITLE
Golem investigating last moved position

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#419]
Currently, golems investigate the last position that they saw the player in. Ideally, they should investigate the last tile that they know the player moved to. If, for instance, the player runs around a line of full-tile walls, the golems are smart enough to understand that the player moved quickly and moved in a particular direction.

**Comment by nsmryan** [comment]
This change will likely modify resolve_ai_attack in resolve.rs.
Currently we use the position that the golem was attacking (the entities position if they are visible) as the position to investigate.
This position is not updated when the player leaves LoS, so the golem investigates the last position they saw the player in.

The problem here is that while we could use the player's current position, this wouldn't make much sense for blink movements. However, the golem has no way to know how the player moved- whether it was a normal movement or a blink.

We do have a per-entity messaging system can be used to record events as seen by an entity which might help here.
Something like:
When an entity moves, check for entities that are tracking them. If the movement is not a blink, then queue a messaging describing the movement.

**Comment by nsmryan** [comment]
The easiest thing to do is always allow a golem to know where you moved to on any movement. I implemented that, and I will play test a bit.

**Comment by nsmryan** [comment]
This does seem to work, ignoring the issue with blink.

**Comment by nsmryan** [comment]
I pushed a change that should make this work with blink.

I also tried to fix a bug with infinite investigation where golems could keep investigating sounds cause by other golems. They now avoid doing this if a sound is caused by a golem that they can see.

**Comment by MicroChasm** [comment]
This issue is fixed as far as I can tell. We can reopen if we see it again.
