### ISSUE TITLE
Abilities/Items/Spells

### ISSUE THREAD

**Issue by nsmryan** [nsmryan/RustRoguelike#82]
Just some ideas on items, abilities, spells, things like that:

Soft Feet- don't make more noise when walking on rubble
Sneaky - make less noise when running
Far Sighted (Aka Four Eyes aka Hyperopia)- see one more tile in FOV radius
Red Potion- extra HP (1 or 2)
Push- push an enemy 2 tiles away
Tunnel- move through wall
Force Bubble- push all enemies a tile away
Force Collapse- move all enemies towards you (perhaps killing you if they are on your tile)
Swap- swap positions with an enemy
De-animate- turn an enemy into an inanimate statue
Re-animate- turn a statue into an enemy
Reform- turn rubble into a wall, perhaps temporarily
Deform - turn a wall/statue into rubble
Explode- kill an enemy, creating tiles all around it. this creates a lot of noise, and hurts you if they are right next to you 
Invisible- enemies can hear you, and will investigate your position, but can't move into attacking you
Incorporeal- you are invisible and make no noise, but perhaps doesn't last long

**Comment by j0e1GMR** [comment]
Blink- moved to a random nearby tile within LOS, or maybe you can choose the general direction
BatForm- fly briefly, move at run speed
Entomb- create walls all around your character. Maybe short walls, or large walls that dissipate over time, letting monsters wander away?
Mist- reduces LOS by a tile
Grassblade- creates a dagger or maybe a sword
Grow grass- softens rubble tiles in an area so that they do not make extra noise. Softens regular tiles so that you can run on them without making extra noise? Or maybe land on them after jumping a wall without making extra noise?
Lithomancer- move stones/walls, create rubble
Golemancer- create your own version of a monster, with a simple ruleset, like it just moves forward until it hits something.

**Comment by j0e1GMR** [comment]
If you move from one tile adjacent to a monster to another tile adjacent to the same monster, that monster will be stunned for one turn. 
Rage/Surge- for a few turns you can make all sorts of actions that would normally take a point of energy
Dampen sound- all sound in an area is lessened
Song of Delving- reveals nearby environment pieces that you cannot see
Song of Mastery- prevents monsters from taking an action on occasion 
Magic Shield- create shield around you that blocks attacks
Imbue weapon- gives a special ability to a temporary weapon, maybe the type of ability that usually only an artifact weapon would have
Parry- if attacked while wielding a sword, you will block the attack. 
Shield bash- use shield to push back monsters. Has to be different from regular pushing somehow
Portal- connect two tiles to one another

**Comment by MicroChasm** [comment]
move four tiles silently, but you have to end the turn on a tile not adjacent to any walls
move four tiles, making a noise at the starting tile
create a straight line that blocks all LOS
Explode lantern, stunning nearby golems
Weaken a full-tile wall by cracking the stone, so that it can be pushed over onto a golem
increase lantern light radius
Create an extra tile in between two tiles, which you can step on. When you are on this tile, you can't take any action and no golem can see you
throw an object which makes continuous sound for a while
all sounds you make are offset by two tiles, or maybe delayed by two turns
you run towards a full-tile wall or column, run up it and kick off, jumping over obstacles and moving four tiles in the opposite direction
Move three tiles, without being visible through in-between tiles
all golems forget your current position
all golems know your current position
briefly step forward 1000 years, all golems are still around but most walls are rubble
chance to dodge golems ranged attacks
redirect a golem ranged attack
insert a new, empty row or column (maybe not empty), which pushes existing tiles away
turn to day-- all tiles not blocked by walls are visible
you can see through stone
as long as you are adjacent to a wall, there is a chance that golems will not see you (maybe you need to be backed by a wall from their perspective?)
create an illusionary version of yourself, who acts on their own goals for a short while
create an illusionary wall that golems will respect, but you can move through

**Comment by MicroChasm** [comment]
new class idea-- The Hierophant. Mostly I just think its a neat word.
the abilities would have to do with light and vision and be related to the sun.

**Comment by nsmryan** [comment]
I also like the work hierophant, and I think a light/information character sounds interesting.

Ideas:
Grass shoes- on a grass tile, the grass attaches to your feet (removing from the tile), and makes you movements silent for a few turns. When it wears off, the grass goes on the current tile.
En-light-en - creates a light that allows you to see some tiles around in your FOV, and maintains this vision for a time even if you walk away.
Mechanic - add a switch to a wall so you can step on the switch to lower and then raise the wall.
Vines- shoot vines onto a wall. The wall can now be traversed by the player by climbing up and down, probably in a single turn.
Crack the Stone - destroys a wall, making a huge sound which will alert much of the level.
Adhere - collect rubble on a tile into a short wall.

**Comment by MicroChasm** [comment]
Grass character is resource management 
Athletic is movement-based
Hierophant is vision/information
Fist character is based on walls and LOS

**Comment by MicroChasm** [comment]
Throw an item and then teleport to that location
throw an item and have vision at the location
throw an item and grow grass at that location
drop or throw an item that distorts space so that the tile it is on is no longer part of the game for a while


Turn an item to grass, including rubble

**Comment by MicroChasm** [comment]
Every action you take makes one tile extra noise, but special actions only use one-half energy point
You can open a portal door in a full-tile wall and enter it. Inside there is a random assortment of items
You can block out all light in the level one time per level. While the light is out you have no LOS, but you can still see stuff in fog of war. While the light is out, you make no noise.
For a certain number of turns, you and all golems can see and walk through all walls
Lose all but one energy. For the rest of the level, you can take two actions per turn
You can select a golem to hold in place for a few turns
For one turn, you can hear/see a ping of sound from every golem on the level 
A fountain of water pools up from one tile. That tile is impassable, and the water makes a river in a random direction, making tiles that have to be jumped over.
Hierophant-- can call down a ray of death that destroys one golem
You can see everything on a set of tiles in a chosen row, column, or diagonal
You can make the sun appear, and the whole level will be visible both for you and for all golems
You create an ambient sound across an area of the level, which masks the sound of your movements
You do a sweet move where you press your palm to the ground. A symbol grows around your tile, and time stops for everyone but you in the symbol. If you move out of the symbol, time resumes, and the symbol shrinks over several turns. 
You hold a spherical, rotating metal astrolabe. You can light the center, and it will project points of light like stars around the level. There is a chance each turn that golems are unable to act when in view of these lights (if they view them directly, not if their backs are turned).

**Comment by MicroChasm** [comment]
If there is a golem in the path of your movement, you move past them, and push them back one tile
You bob and weave-- you can move past golems 
You fold yourself into the wind-- you can now move one extra tile going in the direction of the level's wind, but one fewer going in the opposite direction.

**Comment by MicroChasm** [comment]
Sound Barrier-- the player creates an inter-tile wall which anything can pass through, but which blocks any sound. Sound can still go around the corners a bit, but not through the wall.
A trap which pushes everything two or three tiles away from itself, without directly causing any damage
An object that can be thrown, and walked over, but which blocks any projectiles that attempt to move through its tile

**Comment by MicroChasm** [comment]
Passives--
When you vault an inter-tile wall, you roll an extra tile
+1 LOS
-1 LOS
You can hear golems sounds as if they made one additional tile of noise
You have no abilities, but can use items at 1/2 energy cost
You cannot use items but have +2 ability slots

**Comment by nsmryan** [comment]
I added grass shoes, lanterns as an item, and a Hierophant class with an 'illuminate' skill that just illuminates a few squares around the location.

**Comment by nsmryan** [comment]
I also added a heal skill for the hierophant.

**Comment by MicroChasm** [comment]
this discussion is moved to the design document.
