### ISSUE TITLE
Proposed interaction setup change

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#83]
I had a thought about how the player interacts with the game. Here is an outline of the proposed new system:

Player interactions include-- 
switching between modes (sneaking/walking): "z" and "c"
choosing the direction of their movement: numpad
switching between two stored items: "a" and "s"
interacting with the environment in some way: "e"
switching to "energy mode": shift
use a power or ability: interaction is TBD

In this proposed setup, the player can only sneak or walk. When they move to power mode, they regular actions have a new capacity added. For instance, moving to open space while sneaking makes a two-tile soft move. Moving to a short wall in sneak mode does a soft wall-jump. Moving in walking mode does a three-tile move? Or a two-tile move if over a wall. 
Moving into an enemy in power mode allows you to push the enemy. 
Maybe moving towards and enemy while wielding a shield pushes them back, but in power mode it pushes them two tiles. 
Moving to a wall in power mode while wielding a hammer smashes the wall.
Moving towards an enemy with a dagger in power mode destroys the enemy, but also the dagger.

The benefit of this setup is that the interaction is easy, using only a few keys. The player does have to be aware of their modes at all times though.

**Comment by nsmryan** [comment]
I just found this issue again. A lot of this is not currently implemented:
Interaction with the environment is 'a' instead of 'e'. Easy to change if we want.
Using power or ability is 's'.
There is still sneaking/walking/running, not just sneaking/walking.
Energy is in the game, but there is no 'energy mode'. Instead energy is used up by skills. I think the energy mode concept is interesting, and does keep the interactions simple by reusing interactions with different effects.

How do we want to proceed with this?

**Comment by nsmryan** [comment]
This may be obsolete now that we have reworked the input system.
