### ISSUE TITLE
Push past walls

### ISSUE THREAD

**Issue by MicroChasm** [nsmryan/RustRoguelike#97]
Because of how the player pushes monsters, the player cannot diagonally push a monster into a single-tile wall. Whether the monster is vertically, horizontally, or diagonally adjacent to the wall, if the player is diagonal to the monster, they will always slide past the wall. 
![scenario2](https://user-images.githubusercontent.com/4422963/78315478-f72c7080-7511-11ea-9c1d-6f75b9957fd7.PNG)
![scenario1](https://user-images.githubusercontent.com/4422963/78315479-f7c50700-7511-11ea-91d1-53e346c1f136.PNG)

**Comment by nsmryan** [comment]
This is very true.

I'm not sure what to do in this case- we could have the monster crushed in each case- as long as there is a wall in that direction to either side.

**Comment by j0e1GMR** [comment]
I think that it is ok to leave the first situation as-is. It's really in the second situation that I would expect the monster to be pushed into the wall, since the wall appears to be along the vector of the push.

**Comment by nsmryan** [comment]
@j0e1GMR: in the second image, what should happen if the wall that is to the left of the monster where vertical on the right of that tile instead of on the bottom of the tile?

It seems like this should also result in crushing the monster- it is just the vertical case of the displayed horizontal case.

If so, i think the check is to check if the monster where above its position and moved to the pushed position, would it hit a wall, and if it where to the left of its position and moved to the pushed position, would it hit a wall.
This would have to be checked based on the direction of the diagonal- up-left movement checks up and left, down-right movement checks down and right, etc.

**Comment by j0e1GMR** [comment]
I agree, that scenario should also crush the monster. I think that is the intuition here is that the monster is "catching" on the wall instead of sliding past.

**Comment by MicroChasm** [comment]
This is resolved
